### ISSUE TITLE
Determine product browser support

### ISSUE THREAD

**Issue by stratabuild** [stratasan/wrike-test#109]
**The Problem we are trying to solve** 
Developers need to know what browsers we should support based on user usage

**More about the problem**
For last 180 days as of 8/10/20: 
_﹍Percentages are rounded﹍_
Chrome: 80%
IE: 12%
Firefox: 4%
Edge: 2%
Safari: 2%

**Risks** 
Alienating users who may not use a preferred browers

**Assumptions**
Users browser preferences will stay the same

**User Story**
As a Developer I want to know what browsers we should focus on supporting so we can better serve our customers as they encounter issues.

**_Based on the percentages above focusing on Chrome and IE browser support would be most beneficial._** 
#####

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=492615234)

**Comment by stratabuild** [comment]
➤ Daniel Dreaden commented:

Please leave your contact information
Name
Lisa French

Email
lisa@stratasan.com

Type of request
Other Request

Who is this request for?
Product team

Is the client on the Red/Yellow report?
No

What is the request?
It would be helpful for the development team and for contracts to decide on the browsers we support and the lowest version of each browser that we support, based on an analysis by the product team of client browser usage. 

Why is the request needed?
This request would be helpful for the development team because certain tech features do not work in certain browsers. This would be helpful for contracts, like if a user was having trouble using our application on IE7, we can say that we don't support that browser and our code is not intended or guaranteed to work on that browser.

See Slack thread here: https://stratasan.slack.com/archives/C8DG3PJH0/p1586441601031200

How often do you hear this request?
Sometime

When is this request needed by?
Not urgent > 6 Weeks

Request For
Other

Add screenshots or other files to help

Links to queries/reports

**Comment by daniel-stratasan** [comment]
@lisafrench We can always pull this info out of Pendo.  I have notes above from August when I looked at the data then. Do you need anything else on this?

**Comment by lisafrench** [comment]
@daniel-stratasan Yeah, the August notes answered my question. I have a few notes though:

Are we able to see what versions of IE people are using? Last I heard, we only support IE 11 and up.

We should note that Microsoft is stopping support of IE11 in August of 2021 ([link](https://redmondmag.com/articles/2020/08/17/end-of-support-ie11-and-edgehtml.aspx)). We might make a ticket to prompt users to upgrade from IE to Microsoft Edge, but we could still allow them to use the app if they exit out of that prompt. And/or we will need to make customer success aware that we will no longer support IE11 after August 2021 (if we want to go that route) in case people have issues with our app. Hopefully, we are in the habit of asking users what browser they have already when there is an issue.

This info might be good to document somewhere for both dev and the company so we have a known and agreed-upon browser support standard. Also, most importantly, our browser support should probably be (or may already be) documented in our contracts.

Those are my thoughts. So in summary, what I would like to see happen from this ticket:
- [ ] see in Pendo what versions of IE are being used
- [ ] figure out how to communicate to users that we no longer support a browser
- [ ] figure out how to communicate to the company (especially devs and CS) what browsers we support
- [ ] figure out how we can add or update browser support in our sales contracts

**Comment by lisafrench** [comment]
@clawdyne I had some questions in the last comment on this ticket. Are we just closing out all tickets in this repo?

**Comment by clawdyne** [comment]
Yes, these are dupes created from Wrike to repo write-test.
Thanks,
Christian

*Christian Lawrence *| Sr. Product Manager

Stratasan

450 10th Cir N | Nashville, TN 37203

Office: 866-628-5051

stratasan.com <http://www.stratasan.com/> | Twitter
<https://twitter.com/stratasan> | LinkedIn
<http://www.linkedin.com/company/stratasan>
