### ISSUE TITLE
Update strategic_delivery database tables Nov 2020

### ISSUE THREAD

**Issue by stratabuild** [stratasan/wrike-test#131]
##### Please leave your contact information
**Name**
Jennifer Beck

**Email**
jenniferbeck@stratasan.com

**Type of request**
Other Request

**Who is this request for?**
CHS

**Is the client on the Red/Yellow report?**
Yes

**What is the request?**
Alex update tables in strategic_delivery schema:
1. rename strategic_delivery.chs_state_zips as strategic_delivery.chs_state_zips_2020_archive
2. (re) create strategic_delivery.chs_state_zips
3. insert rows from csv file into strategic_delivery.chs_state_zips

**Why is the request needed?**
CHS requests two kinds of quarterly Enterprise Standard Reports: (1) IPSAF, (2) State/HSAF. Jen Beck produces these reports using a combination of SQL, VBA, and manual manipulation. CHS frequently changes facility names, regions, markets, and service areas; therefore, the database tables supporting these reports need to be periodically updated.

**How often do you hear this request?**
A lot of the time

**When is this request needed by?**
Urgent - within 4 weeks

**Request For**
Other

**Add screenshots or other files to help**
chs_state_zips_11-3-2020.csv
strategic_delivery_script.sql

**Links to queries/reports**
K:\CHS\Projects\Enterprise\Enterprise Summary Reports
### Urgent Request - Need w/in 4 weeks
**Why is this an urgent request?**
In the past, I did not need to create an intake request, because Alex was a manager.

**Since this is an urgent request, please alert the product team about it in the #product slack channel. Did you do that?**
Yes

**What date is this needed by?**
2020-11-05

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=588856081)
┆Attachments: <a href="https://share.unito.io/QcLoiU-9fMwK7qok6nhnzikj3ukYryuhNimHGLJ9mRsZ">chs_state_zips_11-3-2020.csv</a> | <a href="https://share.unito.io/N0AiSmB77auIqOLVEtKlw7nKFhuCrHr5Lfm4l5-QTKN0">strategic_delivery_script.sql</a>

**Comment by stratabuild** [comment]
➤ Christian Lawrence commented:

Jen B why is this needed by November 5? Is there a way to get this moved out to at least next week?

**Comment by stratabuild** [comment]
➤ Christian commented:

@alex-strat the 11/5 date is not something we are working towards at the moment as we need to release 2019 HSAF first which has issues we need to resolve.

**Comment by stratabuild** [comment]
➤ Christian Lawrence commented:

From Hank Neuhoff via Slack: So my take is that 11/5 can be extended at this point because no notification has gone out that HSAF 2019 is available for use. but as soon as that email goes out, we have a lot of work to do for CHS

**Comment by stratabuild** [comment]
➤ Christian Lawrence commented:

https://stratasan.slack.com/archives/C8DG3PJH0/p1604445740067100

**Comment by clawdyne** [comment]
Here is the ticket in Zenhub as the synced one is broken. https://app.zenhub.com/workspaces/data-services-5e5d58abc12d34ca525e0343/issues/stratasan/peach/1796 it's got a .5 on it
